//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardPekus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idiomas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idiomas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DashboardPekus.Resources.Idiomas", typeof(Idiomas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anual.
        /// </summary>
        public static string Anual {
            get {
                return ResourceManager.GetString("Anual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelado.
        /// </summary>
        public static string Cancelado {
            get {
                return ResourceManager.GetString("Cancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIAS MAIS VENDIDAS.
        /// </summary>
        public static string CategoriasMaisVendidas {
            get {
                return ResourceManager.GetString("CategoriasMaisVendidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluido.
        /// </summary>
        public static string Concluido {
            get {
                return ResourceManager.GetString("Concluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string Configuracoes {
            get {
                return ResourceManager.GetString("Configuracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        public static string Dashboards {
            get {
                return ResourceManager.GetString("Dashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde o mês passado.
        /// </summary>
        public static string Desde_o_mês_passado {
            get {
                return ResourceManager.GetString("Desde o mês passado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eletronicos.
        /// </summary>
        public static string Eletronicos {
            get {
                return ResourceManager.GetString("Eletronicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTATÍSTICAS DE VENDAS.
        /// </summary>
        public static string EstatisticasVendas {
            get {
                return ResourceManager.GetString("EstatisticasVendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este mês.
        /// </summary>
        public static string EsteMes {
            get {
                return ResourceManager.GetString("EsteMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Relatório.
        /// </summary>
        public static string ExportarRelatorio {
            get {
                return ResourceManager.GetString("ExportarRelatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casa.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucro.
        /// </summary>
        public static string Lucro {
            get {
                return ResourceManager.GetString("Lucro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensal.
        /// </summary>
        public static string Mensal {
            get {
                return ResourceManager.GetString("Mensal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mês Passado.
        /// </summary>
        public static string MesPassado {
            get {
                return ResourceManager.GetString("MesPassado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moveis.
        /// </summary>
        public static string Moveis {
            get {
                return ResourceManager.GetString("Moveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painel de controle.
        /// </summary>
        public static string PainelControle {
            get {
                return ResourceManager.GetString("PainelControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos Recentes.
        /// </summary>
        public static string PedidosRecentes {
            get {
                return ResourceManager.GetString("PedidosRecentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente.
        /// </summary>
        public static string Pendente {
            get {
                return ResourceManager.GetString("Pendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string Pesquisar {
            get {
                return ResourceManager.GetString("Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receita.
        /// </summary>
        public static string Receita {
            get {
                return ResourceManager.GetString("Receita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumo Mês.
        /// </summary>
        public static string ResumoMes {
            get {
                return ResourceManager.GetString("ResumoMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roupas.
        /// </summary>
        public static string Roupas {
            get {
                return ResourceManager.GetString("Roupas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semanal.
        /// </summary>
        public static string Semanal {
            get {
                return ResourceManager.GetString("Semanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela Cliente.
        /// </summary>
        public static string TabelaCliente {
            get {
                return ResourceManager.GetString("TabelaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela Pedido.
        /// </summary>
        public static string TabelaPedido {
            get {
                return ResourceManager.GetString("TabelaPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela Status.
        /// </summary>
        public static string TabelaStatus {
            get {
                return ResourceManager.GetString("TabelaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela Valor.
        /// </summary>
        public static string TabelaValor {
            get {
                return ResourceManager.GetString("TabelaValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendas.
        /// </summary>
        public static string Vendas {
            get {
                return ResourceManager.GetString("Vendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendas Totais.
        /// </summary>
        public static string Vendas_Totais {
            get {
                return ResourceManager.GetString("Vendas Totais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Todos.
        /// </summary>
        public static string VerTodos {
            get {
                return ResourceManager.GetString("VerTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizações.
        /// </summary>
        public static string Visualizacoes {
            get {
                return ResourceManager.GetString("Visualizacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizações.
        /// </summary>
        public static string Visualizações {
            get {
                return ResourceManager.GetString("Visualizações", resourceCulture);
            }
        }
    }
}
